# Generated by Django 2.2.2 on 2019-06-20 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.CharField(max_length=4)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('education', models.CharField(blank=True, choices=[('', ''), ('High School', 'High School'), ('Vocational School', 'Vocational School'), ('Community College', 'Community College'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('MBA', 'MBA'), ('PhD', 'PhD')], max_length=25)),
                ('education_major', models.CharField(blank=True, max_length=250)),
                ('current_location', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('image', models.ImageField(upload_to='employer/%Y/%m/%d')),
                ('thumb', models.ImageField(blank=True, upload_to='employer/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_type', models.CharField(blank=True, choices=[('University', 'University'), ('High School', 'High School'), ('Middle School', 'Middle School'), ('Primary School', 'Primary School'), ('Kindergarten', 'Kindergarten'), ('Youth Language Center', 'Youth Language Center'), ('Adult Language Center', 'Adult Language Center')], max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='candidate/%Y/%m/%d')),
                ('document_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=1)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
    ]
